version: '3.3'

services:
  wordpress:
     ports:
      - ${WORDPRESS_PORT}:80
  adminer:
    ports:
      - ${ADMINER_PORT}:8080
  mailhog:
    ports:
      - ${MAILHOG_PORT}:1025
      - ${MAILHOG_WEB_PORT}:8025