version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      TZ: ${TIMEZONE}
  wordpress:
    build:
      context: .
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        XDEBUG_MODE: ${XDEBUG_MODE}
        XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
    volumes:
      - ${WORDPRESS_VOLUME}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASS}
      WORDPRESS_DB_NAME: ${DATABASE}
      WP_DEBUG: ${WP_DEBUG}
      TZ: ${TIMEZONE}
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
  mailhog:
    image: mailhog/mailhog